#!/bin/bash
# alipoor90@gmail.com
#bar, the Btrfs ARchiver!
#################################################
dir="${1%/}"
compression="compress-force=zlib"
creation_status="false"

if [[ "$UID" != "0" ]]; then echo "You should run this as root, exiting..."; exit 1 ; fi
ls "$dir".bar >/dev/null 2>&1 ; if [[ "$?" = "0" ]]; then echo "A file with same name exist, exiting..."; exit 1 ; fi

tempfile=$(mktemp -p.)
tempdir=$(mktemp -dp.)
dirsize=$(cut -f1 <<<"$(du -s "$dir")")
dirsize=$(bc <<<"$dirsize * 2")
if [ "$dirsize" -lt "17000" ]; then dirsize="17000"; fi
#################################################
#################################################
#################################################
truncate "$tempfile" --size="$dirsize"KB &&
mkfs.btrfs "$tempfile" &&
mount -tbtrfs "$tempfile" "$tempdir" -o "$compression" &&
rsync -acAXS "$dir" "$tempdir"/ && sleep 0.1 &&
btrfs property set "$tempdir" ro true && sleep 0.1 &&
diff -r "$tempdir"/"$dir"/ "$dir"/ && sleep 2 &&   #Yeah, really that much paranoid!
umount "$tempdir" && sleep 2 &&
dd conv=sparse if="$tempfile" of=""$dir".bar" && 
creation_status="true"
#################################################
rm -f "$tempfile" || echo "Cannot clean temporary files"
rm -rf "$tempdir" || echo "Cannot clean temporary files"
if [[ "$creation_status" = "false" ]]; then rm -f "$dir".bar || echo "Cannot clean temporary files"; fi 
if [[ "$creation_status" = "true" ]]; then echo ""$dir".bar Successfully created!" && exit 0 ; else echo "Unexpected error occurred, failed to create archive" && exit 1 ; fi 
#################################################
